# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.10.5 on 2017-02-16 08:05
=======
# Generated by Django 1.10.5 on 2017-02-16 07:45
>>>>>>> f4f00cbac0c7c4b9d5f5a6efa70b728107444103
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('guide', models.TextField(verbose_name='하는 법')),
                ('effect', models.CharField(max_length=50, verbose_name='효과')),
                ('link', models.URLField(verbose_name='동영상 링크')),
            ],
=======
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('instruction', models.TextField()),
                ('outcomes', models.TextField()),
                ('links', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
>>>>>>> f4f00cbac0c7c4b9d5f5a6efa70b728107444103
        ),
    ]
