# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('guide', models.TextField(verbose_name='하는 법')),
                ('effect', models.CharField(max_length=50, verbose_name='효과')),
                ('link', models.URLField(verbose_name='동영상 링크')),
            ],
        ),
    ]
